force-app/main/default/objects/OrdenTrabajoDeEstructura__c/OrdenTrabajoDeEstructura__c.object-meta.xml
<CustomObject>
    <label>Orden de Trabajo de Estructura</label>
    <nameField>
        <displayFormat>OTE-{0000}</displayFormat>
        <label>Código</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Ordenes de Trabajo de Estructuras</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/OrdenTrabajoDeEstructura__c/fields/Costo__c.field-meta.xml
<CustomField>
    <fullName>Costo__c</fullName>
    <label>Costo</label>
    <precision>12</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/OrdenTrabajoDeEstructura__c/fields/Estado__c.field-meta.xml
<CustomField>
    <fullName>Estado__c</fullName>
    <label>Estado</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Pendiente</fullName>
            </value>
            <value>
                <fullName>Lista</fullName>
            </value>
            <value>
                <fullName>Imcompleta</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/OrdenTrabajoDeEstructura__c/fields/FechaPrevista__c.field-meta.xml
<CustomField>
    <fullName>FechaPrevista__c</fullName>
    <label>Fecha Prevista</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/OrdenTrabajoDeEstructura__c/fields/Instalador__c.field-meta.xml
<CustomField>
    <fullName>Instalador__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Instalador</label>
    <referenceTo>User</referenceTo>
    <relationshipName>OrdenesDeTrabajoDeEstructuras</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/OrdenTrabajoDeEstructura__c/fields/OrdenCompra__c.field-meta.xml
<CustomField>
    <fullName>OrdenCompra__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Orden de Compra</label>
    <referenceTo>OdenDeCompra__c</referenceTo>
    <relationshipLabel>Ordenes de Trabajo de Estructuras</relationshipLabel>
    <relationshipName>OrdenesDeTrabajoDeEstructuras</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/OrdenTrabajoDeEstructura__c/fields/Proveedor__c.field-meta.xml
<CustomField>
    <fullName>Proveedor__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Proveedor</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Ordenes de Trabajo de Estructuras</relationshipLabel>
    <relationshipName>OrdenesDeTrabajoDeEstructuras</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/OrdenTrabajoDeEstructura__c/fields/Tipo__c.field-meta.xml
<CustomField>
    <fullName>Tipo__c</fullName>
    <label>Tipo</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Instalación</fullName>
            </value>
            <value>
                <fullName>Reparación</fullName>
            </value>
            <value>
                <fullName>Desinstalación</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/ControllerAssociateWorkOrder.cls
public without sharing class ControllerAssociateWorkOrder {
    
     @AuraEnabled
    public static List<ResultWrapper> getOrdenTrabajo(String recordId){
        List<ResultWrapper> listOrdenT = new List<ResultWrapper>();
        OdenDeCompra__c  OC = [Select Proveedor__c from OdenDeCompra__c  Where Id=:recordId];
        for(OrdenTrabajoDeEstructura__c item: 
            [Select Id, Tipo__c, Estado__c, Proveedor__r.Name, Instalador__r.Name,
             FechaPrevista__c, Costo__C from OrdenTrabajoDeEstructura__c
             Where Proveedor__c = :OC.Proveedor__C And OrdenCompra__c = null
            Order by Proveedor__r.Name Asc]){
                 ResultWrapper ordenT = new ResultWrapper();
                 ordenT.id = item.Id;
                 ordenT.tipo = item.Tipo__c;
                 ordenT.estado = item.Estado__c;
                 ordenT.proveedor = item.Proveedor__r.Name;
                 ordenT.instalador = item.Instalador__r.Name;
                 ordenT.fecha = item.FechaPrevista__c != null ? item.FechaPrevista__c.addDays(1) : null ;
                 ordenT.costo = item.Costo__C;
                 listOrdenT.add(ordenT);
             }
        return listOrdenT;
    }
    
    @AuraEnabled
    public static void updateRecord(String jsonString, String recordId){
        List<ResultWrapper> listOrdenT = (List<ResultWrapper>) Json.deserialize(jsonString, List<ResultWrapper>.class);
        List<OrdenTrabajoDeEstructura__c> listOrdenTrabajo = new List<OrdenTrabajoDeEstructura__c>();
        for(ResultWrapper item: listOrdenT){
            listOrdenTrabajo.add(new OrdenTrabajoDeEstructura__c(Id=item.id, OrdenCompra__c = recordId));
        }
        update listOrdenTrabajo;
    }
    
    
    public class ResultWrapper {
        @AuraEnabled public String id{get;set;}
        @AuraEnabled public String tipo{get;set;}
        @AuraEnabled public String estado{get;set;}
        @AuraEnabled public String proveedor{get;set;}
        @AuraEnabled public String instalador{get;set;}
        @AuraEnabled public Date fecha{get;set;}
        @AuraEnabled public Decimal costo{get;set;}
    }
            
            

}