force-app/main/default/objects/Estructura__c/Estructura__c.object-meta.xml
<CustomObject>
    <label>Estructura</label>
    <nameField>
        <label>Nombre de Estructura</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Estructuras</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/EstructuraEnSItio__c/EstructuraEnSItio__c.object-meta.xml
<CustomObject>
    <label>Estructura en Sitio</label>
    <nameField>
        <label>Nombre de Estructura</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Estructuras en Sitios</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/EstructuraEnSItio__c/fields/Estado__c.field-meta.xml
<CustomField>
    <fullName>Estado__c</fullName>
    <label>Estado</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Activa</fullName>
            </value>
            <value>
                <fullName>Inactiva</fullName>
            </value>
            <value>
                <fullName>En Progreso</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/EstructuraEnSItio__c/fields/Estructura__c.field-meta.xml
<CustomField>
    <fullName>Estructura__c</fullName>
    <label>Estructura</label>
    <referenceTo>Estructura__c</referenceTo>
    <relationshipLabel>Estructuras en Sitios</relationshipLabel>
    <relationshipName>EstructurasEnSitios</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/EstructuraEnSItio__c/fields/Medio__c.field-meta.xml
<CustomField>
    <fullName>Medio__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Medio</label>
    <referenceTo>Medio__c</referenceTo>
    <relationshipLabel>Estructuras en Sitios</relationshipLabel>
    <relationshipName>EstructurasEnSitios</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/EstructuraEnSItio__c/fields/Sitio__c.field-meta.xml
<CustomField>
    <fullName>Sitio__c</fullName>
    <formula>Medio__r.Sitio__r.Name</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Sitio</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/OrdenTrabajoDeEstructura__c/OrdenTrabajoDeEstructura__c.object-meta.xml
<CustomObject>
    <label>Orden de Trabajo de Estructura</label>
    <nameField>
        <displayFormat>OTE-{0000}</displayFormat>
        <label>Código</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Ordenes de Trabajo de Estructuras</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/OrdenTrabajoDeEstructura__c/fields/Costo__c.field-meta.xml
<CustomField>
    <fullName>Costo__c</fullName>
    <label>Costo</label>
    <precision>12</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/OrdenTrabajoDeEstructura__c/fields/DetalleReparecion__c.field-meta.xml
<CustomField>
    <fullName>DetalleReparecion__c</fullName>
    <label>Detalle de Repareción</label>
    <length>131072</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/OrdenTrabajoDeEstructura__c/fields/Estado__c.field-meta.xml
<CustomField>
    <fullName>Estado__c</fullName>
    <label>Estado</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Pendiente</fullName>
            </value>
            <value>
                <fullName>Lista</fullName>
            </value>
            <value>
                <fullName>Imcompleta</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/OrdenTrabajoDeEstructura__c/fields/EstructuraEnSitio__c.field-meta.xml
<CustomField>
    <fullName>EstructuraEnSitio__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Estructura en Sitio</label>
    <referenceTo>EstructuraEnSItio__c</referenceTo>
    <relationshipLabel>Ordenes de Trabajo de Estructuras</relationshipLabel>
    <relationshipName>OrdenesDeTrabajoDeEstructuras</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/OrdenTrabajoDeEstructura__c/fields/FechaPrevista__c.field-meta.xml
<CustomField>
    <fullName>FechaPrevista__c</fullName>
    <label>Fecha Prevista</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/OrdenTrabajoDeEstructura__c/fields/Instalador__c.field-meta.xml
<CustomField>
    <fullName>Instalador__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Instalador</label>
    <referenceTo>User</referenceTo>
    <relationshipName>OrdenesDeTrabajoDeEstructuras</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/OrdenTrabajoDeEstructura__c/fields/Medio__c.field-meta.xml
<CustomField>
    <fullName>Medio__c</fullName>
    <formula>EstructuraEnSitio__r.Medio__r.Producto__r.Name + &quot; - &quot;+ EstructuraEnSitio__r.Medio__r.UbicacionEnSitio__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Medio</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/OrdenTrabajoDeEstructura__c/fields/Proveedor__c.field-meta.xml
<CustomField>
    <fullName>Proveedor__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Proveedor</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Ordenes de Trabajo de Estructuras</relationshipLabel>
    <relationshipName>OrdenesDeTrabajoDeEstructuras</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/OrdenTrabajoDeEstructura__c/fields/Tipo__c.field-meta.xml
<CustomField>
    <fullName>Tipo__c</fullName>
    <label>Tipo</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Instalación</fullName>
            </value>
            <value>
                <fullName>Reparación</fullName>
            </value>
            <value>
                <fullName>Desinstalación</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/ControllerRepairAndUninstall.cls
public class ControllerRepairAndUninstall {
    
    @AuraEnabled
    public static ResultWrapper getListOption(String recordId, String medio, String sitio){
        ResultWrapper result = new ResultWrapper();
        
        result.listSitios = new List<PicklistOption>();
        result.listMedios = new List<PicklistOption>();
        
        result.listSitios.add(new PicklistOption('--Ninguno--', ''));
        result.listMedios.add(new PicklistOption('--Ninguno--', ''));
        
        result.sitio='';
        result.medio = '';
        result.botonDesabilitado = false;
        List<String> listaControl = new List<String>();
        for(OrdenTrabajoDeEstructura__c item: [Select Tipo__c, Estado__c,Id, Medio__c,EstructuraEnSitio__r.Medio__r.Sitio__c, EstructuraEnSitio__r.Medio__r.Sitio__r.Name from OrdenTrabajoDeEstructura__c where EstructuraEnSitio__r.Estructura__c =: recordId Order  by EstructuraEnSitio__r.Medio__r.Sitio__r.Name asc]){
            if(!listaControl.contains(item.Medio__c)){
                listaControl.add(item.Medio__c);
                result.listMedios.add(new PicklistOption(item.Medio__c, item.Medio__c)); 
            }
            if(!listaControl.contains(item.EstructuraEnSitio__r.Medio__r.Sitio__c)){
                listaControl.add(item.EstructuraEnSitio__r.Medio__r.Sitio__c);
                result.listSitios.add(new PicklistOption(item.EstructuraEnSitio__r.Medio__r.Sitio__r.Name, item.EstructuraEnSitio__r.Medio__r.Sitio__c)); 
            }
            if(item.Estado__c != 'Lista' && (item.Tipo__c == 'Reparación' || item.Tipo__c == 'Desinstalación') ){
                result.botonDesabilitado = true;
            }
        }
        result.listRecord = getRecords(recordId, medio, sitio, result.botonDesabilitado);
        return result;
    }
    
    @AuraEnabled
    public static List<OrdenTrabajoDeEstructura> getRecords(String recordId, String medio, String sitio, Boolean botonDesabilitado){
        try{
            List<String> listEstructuraSitio = new List<String>();
            for(EstructuraEnSItio__c item: [Select Id from EstructuraEnSItio__c  Where Estructura__c =:recordId and Estado__c = 'Activa']){
                listEstructuraSitio.add(item.Id);
            }
            system.debug('listEstructuraSitio: '+listEstructuraSitio.size());
            List<OrdenTrabajoDeEstructura> listRecord = new List<OrdenTrabajoDeEstructura>();
            String query = 'Select Medio__c,Name,EstructuraEnSitio__r.Medio__r.Name,Instalador__r.Name,'+
                'Tipo__c, Estado__c,EstructuraEnSitio__r.Estado__c,EstructuraEnSitio__r.Medio__r.Sitio__r.Name,EstructuraEnSitio__c,'+
                'Proveedor__r.Name,FechaPrevista__c, Costo__c from OrdenTrabajoDeEstructura__c Where EstructuraEnSitio__c in :listEstructuraSitio ';
               // '  And EstructuraEnSitio__r.Estado__c = \'Activa\'';
            //And Tipo__c = \'Instalación\'
            if(medio != null && medio != ''){
                query +=' And Medio__c = :medio';
            }
            if(sitio != null && sitio != ''){
                query +=' And EstructuraEnSitio__r.Medio__r.Sitio__c = :sitio';
            }
            query +=' Order by EstructuraEnSitio__r.Medio__r.Sitio__r.Name Asc';
            List<OrdenTrabajoDeEstructura__c> listOrdenTE = Database.query(query);
            List<String> listOrdenTERepa = new List<String>();
            for(OrdenTrabajoDeEstructura__c item: listOrdenTE){
                if(item.Estado__c != 'Lista' && (item.Tipo__c == 'Reparación' || item.Tipo__c == 'Desinstalación')){
                    listOrdenTERepa.add(item.EstructuraEnSitio__c);
                }
            }
            system.debug('Query: '+listOrdenTE.size());
            for(OrdenTrabajoDeEstructura__c item: listOrdenTE){
                system.debug('item: '+item);
                OrdenTrabajoDeEstructura record = new OrdenTrabajoDeEstructura();
                record.sitio = item.EstructuraEnSitio__r.Medio__r.Sitio__r.Name;
                record.medio = item.Medio__c;
                record.usuario = item.Instalador__r.Name;
                record.proveedor = item.Proveedor__r.Name;
                record.fecha = item.FechaPrevista__c != null ? item.FechaPrevista__c.addDays(1) : null ;
                record.costo = item.Costo__c;
                record.id = item.Id;
                record.botonDesabilitado = listOrdenTERepa.contains(item.EstructuraEnSitio__c);
                if(item.Tipo__c == 'Instalación'){
                    listRecord.add(record);
                }                
            }
            return listRecord;
        }catch (Exception e) {
            system.debug(e.getMessage());
            throw new AuraHandledException(e.getMessage());
        }
    }
    
    @AuraEnabled
    public static void insertOrdenTrabajo(String recordId, String accion, Date fecha, Decimal costo, String detalle){
        OrdenTrabajoDeEstructura__c ODE = new OrdenTrabajoDeEstructura__c();
        System.debug('recordId: '+recordId);
        for(OrdenTrabajoDeEstructura__c item: 
            [Select Instalador__c, FechaPrevista__c, Costo__c, 
             EstructuraEnSitio__c,Proveedor__c,Estado__c 
             From OrdenTrabajoDeEstructura__c Where Id = :recordId]){
                 ODE.Tipo__c = accion;
                 ODE.Instalador__c = item.Instalador__c;
                 ODE.FechaPrevista__c = fecha;
                 ODE.Costo__c = costo;
                 ODE.Estado__c = 'Pendiente';
                 ODE.EstructuraEnSitio__c = item.EstructuraEnSitio__c;
                 ODE.Proveedor__c = item.Proveedor__c;
                 ODE.DetalleReparecion__c = detalle;
             }
        system.debug(ODE);
        insert ODE;
    }
    
    
    public class ResultWrapper {
        @AuraEnabled public List<OrdenTrabajoDeEstructura> listRecord;
        @AuraEnabled public List<PicklistOption> listMedios{get;set;}
        @AuraEnabled public List<PicklistOption> listSitios{get;set;}
        @AuraEnabled public String sitio{get;set;}
        @AuraEnabled public String medio{get;set;}
        @AuraEnabled public Boolean botonDesabilitado{get;set;}
    }
    
    public class OrdenTrabajoDeEstructura {
        @AuraEnabled public String id{get;set;}
        @AuraEnabled public String medio{get;set;}
        @AuraEnabled public String sitio{get;set;}
        @AuraEnabled public String usuario{get;set;}
        @AuraEnabled public String proveedor{get;set;}
        @AuraEnabled public Date fecha{get;set;}
        @AuraEnabled public Decimal costo{get;set;}
        @AuraEnabled public Boolean botonDesabilitado{get;set;}
    }
    
    public class PicklistOption{
        @AuraEnabled public String label{get;set;}
        @AuraEnabled public String value{get;set;}
        PicklistOption(String label, String value){
            this.label = label;
            this.value = value;
        }
    }

}