force-app/main/default/objects/Estructura__c/Estructura__c.object-meta.xml
<CustomObject>
    <label>Estructura</label>
    <nameField>
        <label>Nombre de Estructura</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Estructuras</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Estructura__c/fields/CantidadBodega__c.field-meta.xml
<CustomField>
    <fullName>CantidadBodega__c</fullName>
    <formula>CantidadTotal__c -  CantidadColocada__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Cantidad en Bodega</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Estructura__c/fields/Producto__c.field-meta.xml
<CustomField>
    <fullName>Producto__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Producto</label>
    <referenceTo>Producto__c</referenceTo>
    <relationshipLabel>Estructuras</relationshipLabel>
    <relationshipName>Estructuras</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/EstructuraEnSItio__c/EstructuraEnSItio__c.object-meta.xml
<CustomObject>
    <label>Estructura en Sitio</label>
    <nameField>
        <label>Nombre de Estructura</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Estructuras en Sitios</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/EstructuraEnSItio__c/fields/Estado__c.field-meta.xml
<CustomField>
    <fullName>Estado__c</fullName>
    <label>Estado</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Activa</fullName>
            </value>
            <value>
                <fullName>Inactiva</fullName>
            </value>
            <value>
                <fullName>En Progreso</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/EstructuraEnSItio__c/fields/Estructura__c.field-meta.xml
<CustomField>
    <fullName>Estructura__c</fullName>
    <label>Estructura</label>
    <referenceTo>Estructura__c</referenceTo>
    <relationshipLabel>Estructuras en Sitios</relationshipLabel>
    <relationshipName>EstructurasEnSitios</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/EstructuraEnSItio__c/fields/Medio__c.field-meta.xml
<CustomField>
    <fullName>Medio__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Medio</label>
    <referenceTo>Medio__c</referenceTo>
    <relationshipLabel>Estructuras en Sitios</relationshipLabel>
    <relationshipName>EstructurasEnSitios</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/EstructuraEnSItio__c/fields/Sitio__c.field-meta.xml
<CustomField>
    <fullName>Sitio__c</fullName>
    <formula>Medio__r.Sitio__r.Name</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Sitio</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/OrdenTrabajoDeEstructura__c/OrdenTrabajoDeEstructura__c.object-meta.xml
<CustomObject>
    <label>Orden de Trabajo de Estructura</label>
    <nameField>
        <displayFormat>OTE-{0000}</displayFormat>
        <label>Código</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Ordenes de Trabajo de Estructuras</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/OrdenTrabajoDeEstructura__c/fields/Costo__c.field-meta.xml
<CustomField>
    <fullName>Costo__c</fullName>
    <label>Costo</label>
    <precision>12</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/OrdenTrabajoDeEstructura__c/fields/Estado__c.field-meta.xml
<CustomField>
    <fullName>Estado__c</fullName>
    <label>Estado</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Pendiente</fullName>
            </value>
            <value>
                <fullName>Lista</fullName>
            </value>
            <value>
                <fullName>Imcompleta</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/OrdenTrabajoDeEstructura__c/fields/EstructuraEnSitio__c.field-meta.xml
<CustomField>
    <fullName>EstructuraEnSitio__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Estructura en Sitio</label>
    <referenceTo>EstructuraEnSItio__c</referenceTo>
    <relationshipLabel>Ordenes de Trabajo de Estructuras</relationshipLabel>
    <relationshipName>OrdenesDeTrabajoDeEstructuras</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/OrdenTrabajoDeEstructura__c/fields/FechaPrevista__c.field-meta.xml
<CustomField>
    <fullName>FechaPrevista__c</fullName>
    <label>Fecha Prevista</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/OrdenTrabajoDeEstructura__c/fields/Instalador__c.field-meta.xml
<CustomField>
    <fullName>Instalador__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Instalador</label>
    <referenceTo>User</referenceTo>
    <relationshipName>OrdenesDeTrabajoDeEstructuras</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/OrdenTrabajoDeEstructura__c/fields/Medio__c.field-meta.xml
<CustomField>
    <fullName>Medio__c</fullName>
    <formula>EstructuraEnSitio__r.Medio__r.Producto__r.Name + &quot; - &quot;+ EstructuraEnSitio__r.Medio__r.UbicacionEnSitio__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Medio</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/OrdenTrabajoDeEstructura__c/fields/Proveedor__c.field-meta.xml
<CustomField>
    <fullName>Proveedor__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Proveedor</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Ordenes de Trabajo de Estructuras</relationshipLabel>
    <relationshipName>OrdenesDeTrabajoDeEstructuras</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/OrdenTrabajoDeEstructura__c/fields/Tipo__c.field-meta.xml
<CustomField>
    <fullName>Tipo__c</fullName>
    <label>Tipo</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Instalación</fullName>
            </value>
            <value>
                <fullName>Reparación</fullName>
            </value>
            <value>
                <fullName>Desinstalación</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/ControllerAssignStructures.cls
public without sharing class ControllerAssignStructures {
    
    @AuraEnabled
    public static ResultWrapper getListOption(String recordId){
        try{
            ResultWrapper result = new ResultWrapper();
            result.listMedios = new List<PicklistOption>();
            result.listSitios = new List<PicklistOption>();
            result.listUsuarios = new List<PicklistOption>();
            result.listProveedores = new List<PicklistOption>();
            result.fecha = System.today();
            Map<String, String> mapSitio = new map<String, string>();
            Estructura__c estructura = [Select Id,Name, Producto__c,Producto__r.Name,CantidadBodega__c from Estructura__c Where Id = :recordId ];
            for(Medio__c item: [Select Id, Name, Sitio__r.Name,Sitio__c, UbicacionEnSitio__c ,Producto__r.Name from Medio__c Where Producto__c =:estructura.Producto__c
                                order by Name, Sitio__r.Name asc ]){
                                    //result.listMedios.add(new PicklistOption(item.Producto__r.Name+' - '+item.UbicacionEnSitio__c, item.Id));
                                    if(!mapSitio.containsKey(item.Sitio__c)){
                                        mapSitio.put(item.Sitio__c, item.Sitio__r.Name);
                                        result.listSitios.add(new PicklistOption(item.Sitio__r.Name, item.Sitio__c));
                                    }
                                }
            for(User item: [Select Id, Name from User Where Profile.Name = 'Administrador del sistema']){
                result.listUsuarios.add(new PicklistOption(item.Name, item.Id));
            }
            for(Account item: [Select Id, Name from Account Where RecordType.Name = 'Proveedor']){
                result.listProveedores.add(new PicklistOption(item.Name, item.Id));
            }
            result.id = estructura.Id;
            result.nombreEstructura = estructura.Name;
            result.nombreProducto = estructura.Producto__r.Name;
            result.asignacionesDisponibles = estructura.CantidadBodega__c;
            result.disabledBoton = estructura.CantidadBodega__c > 0 ? false : true;
            system.debug(result.listMedios.size() +' - '+result.listSitios.size() +' - '+result.listUsuarios.size() +' - '+result.listProveedores.size());
            return result;
        }catch (Exception e) {
            throw new AuraHandledException(e.getMessage());
        }
    }
    
    @AuraEnabled
    public static List<PicklistOption> getMedium(String sitioId){
        List<PicklistOption> listMedios = new List<PicklistOption>();
        for(Medio__c item: 
            [Select Id, Name, Sitio__r.Name,Sitio__c, UbicacionEnSitio__c ,Producto__r.Name from Medio__c Where Sitio__c =: sitioId
             order by Name, Sitio__r.Name asc ]){
                 listMedios.add(new PicklistOption(item.Producto__r.Name+' - '+item.UbicacionEnSitio__c, item.Id));
             }
        return listMedios;
    }
    
    @AuraEnabled
    public static List<PicklistOption> getInstalador(String sitioId){
        List<PicklistOption> listInstalador = new List<PicklistOption>();
        for(Sitio__c item: 
            [Select Id, Ruta__r.Usuario__c, Ruta__r.Usuario__r.Name from Sitio__c Where Id =: sitioId ]){
                 listInstalador.add(new PicklistOption(item.Ruta__r.Usuario__r.Name, item.Ruta__r.Usuario__c));
             }
        return listInstalador;
    }
    
    @AuraEnabled
    public static void insertRecord(String data){
        try{
            ResultWrapper dataObj = (ResultWrapper)System.JSON.deserialize(data, ResultWrapper.class);
            EstructuraEnSItio__c EES = new EstructuraEnSItio__c();
            EES.Estado__c = 'En Progreso';
            EES.Name = dataObj.nombreEstructura + ' - '+dataObj.nombreProducto;
            EES.Estructura__c = dataObj.id;
            EES.Medio__c = dataObj.medioSelecionado;
            for(PicklistOption item : dataObj.listSitios){
                if(item.value == dataObj.sitioSelecionado){
                    EES.Name +=' - '+item.label;
                    break;
                }
            }
            for(Medio__c item:
                [Select UbicacionEnSitio__c from Medio__c Where Sitio__c =: dataObj.sitioSelecionado And
                 Id=: dataObj.medioSelecionado order by Name, Sitio__r.Name asc ]){
                     EES.Name += ' - '+item.UbicacionEnSitio__c;
                 }
            insert EES;
            OrdenTrabajoDeEstructura__c ODE = new OrdenTrabajoDeEstructura__c();
            ODE.Tipo__c = 'Instalación';
            ODE.Instalador__c = dataObj.usuarioSelecionado;
            ODE.FechaPrevista__c = dataObj.fecha;
            ODE.Costo__c = dataObj.costo;
            ODE.Estado__c = 'Pendiente';
            ODE.EstructuraEnSitio__c = EES.Id;
            ODE.Proveedor__c = dataObj.proveedorSelecionado;
            insert ODE;
            if(String.isNotBlank(ODE.Proveedor__c)){
                String recordTypeOC = Schema.SObjectType.OdenDeCompra__c.getRecordTypeInfosByDeveloperName().get('MantenimientoEstructuras').getRecordTypeId();
                OdenDeCompra__c orden = new OdenDeCompra__c(RecordTypeId = recordTypeOC, Estado__c = 'Borrador');
                insert orden;
            }
        }catch (Exception e) {
            system.debug(e.getMessage()+' --- '+e.getLineNumber());
            throw new AuraHandledException(e.getMessage());
        }
    }
    
    
    public class ResultWrapper {
        @AuraEnabled public String id{get;set;}
        @AuraEnabled public String nombreEstructura{get;set;}
        @AuraEnabled public String nombreProducto{get;set;}
        @AuraEnabled public String medioSelecionado{get;set;}
        @AuraEnabled public String sitioSelecionado{get;set;}
        @AuraEnabled public String usuarioSelecionado{get;set;}
        @AuraEnabled public String proveedorSelecionado{get;set;}
        @AuraEnabled public Boolean disabledBoton{get;set;}
        @AuraEnabled public Decimal asignacionesDisponibles{get;set;}
        @AuraEnabled public Date fecha{get;set;}
        @AuraEnabled public Decimal costo{get;set;}
        @AuraEnabled public List<PicklistOption> listMedios{get;set;}
        @AuraEnabled public List<PicklistOption> listSitios{get;set;}
        @AuraEnabled public List<PicklistOption> listUsuarios{get;set;}
        @AuraEnabled public List<PicklistOption> listProveedores{get;set;}
    }
    
    public class PicklistOption{
        @AuraEnabled public String label{get;set;}
        @AuraEnabled public String value{get;set;}
        PicklistOption(String label, String value){
            this.label = label;
            this.value = value;
        }
    }

}